version: '3.1'

services:

  elasticsearch:
    build:
      context: ./
      dockerfile: dockerfile_elasticsearch
    image: elasticsearch:5.6.11
    ports:
    - 9200:9200

  kibana:
    image: kibana:5.6.12
    ports:
    - 5601:5601
